# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9a2fbf6644f99ea9dd73d42feb8574dc80e7b358c4d343967d6fe307f6db6e29534d614088dc02af86c323c55bd885fb5d34874a16653406a2ed56104b5cdd9

test:
  secret_key_base: 0b643503ca701e97ca1342b0d64ec3bfb32e5dd7611baee24e4a0fb0aa56a920c16a51097abff58b78c2dcb9050ca1daefa12a80170fc607d612a07e1d58072f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
  DROPBOX_APP_KEY: <%= ENV["DROPBOX_APP_KEY"] %>
  DROPBOX_APP_SECRET: <%= ENV["DROPBOX_APP_SECRET"] %>
  DROPBOX_ACCESS_TOKEN: <%= ENV["DROPBOX_ACCESS_TOKEN"] %>
  DROPBOX_ACCESS_TOKEN_SECRET: <%= ENV["DROPBOX_ACCESS_TOKEN_SECRET"] %>
  DROPBOX_USER_ID: <%= ENV["DROPBOX_USER_ID"] %>
